spring:
 application:
  name: gateway-service
  
 cloud:
  gateway:
   routes:
   - id: to_book_service
     uri: http://localhost:7001
     predicates:
     - Path=/book/**
   - id: to_review_service
     uri: http://localhost:7002
     predicates:
     - Path=/review/**,/reviewbybook/**
   - id: to_info_service
     uri: http://localhost:7003
     predicates:
     - Path=/info/**
    
  
server:
 port: 7070
