spring:
 application:
  name: gateway-service
  
 cloud:
  cloud:
  consul:
   enabled: true
   host: consul
   discovery:
    prefer-ip-address: true
    include-hostname-in-instance-id: true
    
  gateway:
   routes:
   - id: to_book_service
     uri: lb://book-service
     predicates:
     - Path=/book/**
   - id: to_review_service
     uri: lb://review-service
     predicates:
     - Path=/review/**,/reviewbybook/**
   - id: to_info_service
     uri: lb://info-service
     predicates:
     - Path=/info/**
    
  
server:
 port: 7070
