spring:
 application:
  name: book-service
 jpa:
  hibernate:
   ddl-auto: none
 datasource:
  initialization-mode: always
  platform: postgres
  url: jdbc:postgresql://dbserver:5432/bookstore
  username: postgres
  password: linux
  
 cloud:
  consul:
   enabled: true
   host: consul
   discovery:
    prefer-ip-address: true
    include-hostname-in-instance-id: true
   
server:
 port: 7001
