spring:
 application:
  name: review-service
 data:
  mongodb:
   host: mongodb
   port: 27017
   database: review 
 
 cloud:
  consul:
   enabled: true
   host: consul
   discovery:
    prefer-ip-address: true
    include-hostname-in-instance-id: true 
  
server:
 port: 7002

